api-version: 1.13
main: io.github.sindastra.BukkitOPPrefix.Main
version: 1.0.1
name: SindastrasOPPrefix
permissions:
    opprefix.show:
        description: Show the OP prefix
        default: false