api-version: 1.13
main: io.github.sindastra.BukkitOPPrefix.Main
version: 1.0.4
author: Sindastra
website: https://github.com/sindastra/BukkitOPPrefix
name: SindastrasOPPrefix
permissions:
    opprefix.show:
        description: Show the OP prefix
        default: false